version: "3.9"

services:
  spk_cli:
    image: mkenjis/ubspkcluster1_img
    volumes:
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    networks:
      - mynet
    depends_on:
      - hdpmst
  hdpmst:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdpmst
    volumes:
      - .:/root/staging
      - name0:/hadoop/hdfs/namenode
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    environment:
      - HADOOP_HOST_SLAVES=hdp1,hdp2,hdp3
    networks:
      - mynet
    depends_on:
      - hdp1,hdp2,hdp3
  hdp1:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp1
    volumes:
      - data1:/hadoop/hdfs/datanode
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    networks:
      - mynet
  hdp2:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp2
    volumes:
      - data2:/hadoop/hdfs/datanode
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    networks:
      - mynet
  hdp3:
    image: mkenjis/ubhdpclu_vol_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdp3
    volumes:
      - data3:/hadoop/hdfs/datanode
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    networks:
      - mynet

networks:
  mynet:
  
volumes:
  name0:
  data1:
  data2:
  data3:
