version: "3.1"

services:
  spk_cli:
    image: mkenjis/ubspkcli_yarn_img
    deploy:
      placement:
        constraints:
          - node.labels.hostlabel == hdpmst
    networks:
      - mynet
    environment:
      - HADOOP_HOST_MASTER=hdpmst
    ports:
      - 4040:4040

networks:
  mynet:
    external:
       name: mynet
